# Generated by Django 5.0.1 on 2024-01-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nucleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('fecha_apertura', models.DateField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('estatus_inmueble', models.CharField(max_length=100)),
                ('infraestructura', models.TextField()),
            ],
        ),
    ]
