# Generated by Django 5.0.1 on 2024-01-18 23:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='direccion',
            field=models.CharField(default='No especificada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumento',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumento',
            name='nombre_persona',
            field=models.CharField(default='No especificada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumento',
            name='numero_expediente_procesal',
            field=models.CharField(default='No especificada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instrumento',
            name='poliza_seguro',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='comodato_vigente',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('na', 'N/A'), ('sc', 'S/C')], default='na', max_length=100),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='condicion',
            field=models.CharField(choices=[('operativo', 'Operativo'), ('inoperativo', 'Inoperativo'), ('danada', 'Dañada'), ('obsoleto', 'Obsoleto'), ('deuso', 'De uso')], default='operativo', max_length=100),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='procedencia',
            field=models.CharField(choices=[('fmsb', 'FMSB'), ('dsr', 'DSR'), ('comodato', 'Comodato'), ('otro', 'Otro')], default='otro', max_length=100),
        ),
    ]
