# Generated by Django 5.0.1 on 2024-01-13 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('catedra', models.CharField(max_length=100)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleos.nucleo')),
            ],
        ),
    ]
