# Generated by Django 5.0.1 on 2024-01-18 21:07

import alumnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion_de_habitacion',
            field=models.CharField(default='No especificada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='estatus',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel_educativo',
            field=models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('superior', 'Superior'), ('ninguno', 'Ninguno')], default='na', max_length=10),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nombre_de_representante',
            field=models.CharField(default='No especificada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='numero_de_telefono',
            field=models.CharField(default='No especificada', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='na', max_length=9),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_sangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='na', max_length=3),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(validators=[alumnos.models.validar_edad]),
        ),
    ]
