# Generated by Django 5.0.1 on 2024-01-13 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('numero_documento', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('cargo', models.CharField(max_length=100)),
                ('funcion', models.CharField(max_length=100)),
                ('nivel_educativo', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('id_personal', models.AutoField(primary_key=True, serialize=False)),
                ('nucleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleos.nucleo')),
            ],
        ),
    ]
