# Generated by Django 5.0.1 on 2024-01-15 20:58

import personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='edad',
            field=models.IntegerField(validators=[personal.models.validar_edad]),
        ),
    ]
