# Generated by Django 5.0.1 on 2024-01-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_personal_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='colateral',
            field=models.CharField(default='No espeficidada', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='direccion_habitacion',
            field=models.TextField(default='No especificada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='estatus',
            field=models.CharField(choices=[('renuncia', 'Renuncia'), ('suspension', 'Suspensión'), ('traslado', 'Traslado')], default='renuncia', max_length=10),
        ),
        migrations.AddField(
            model_name='personal',
            name='talla_camisa',
            field=models.CharField(default='No especificada', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='talla_pantalon',
            field=models.CharField(default='No especificada', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='talla_zapato',
            field=models.CharField(default='No especificada', max_length=50),
            preserve_default=False,
        ),
    ]
